name: fitness_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-178.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+3
  flutter_svg: ^0.22.0
  google_sign_in: ^5.1.1
  firebase_auth: ^3.1.2
  firebase_core: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
